FROM python:3.12.12-slim

# folder inside the docker container and we set /app as the current working directory
# all command runs inside /app container
WORKDIR /app

# copy the dependencies 
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copy backend code
COPY backend/ backend/

# expose FastAPI port
EXPOSE 8000

# start fastapi server
CMD ["uvicorn","backend.server:app","--host","0.0.0.0","--port","8000"]